server:
  port: 18602
eureka:
  instance:
    hostname: localhost
    appname: eureka-center
  client:
    # 单点的时候设置为false 禁止注册自身
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000